### ISSUE TITLE
The compatible issue between MMM-SmartWebDisplay and Home Assistant

### ISSUE THREAD

**Issue by xuepgao** [AgP42/MMM-SmartWebDisplay#4] opened 2019-04-09 15:23 UTC
@AgP42 

Thanks your module.
I installed and configured Home Assistant on Raspberry Pi 3b+. Now I found there is a little compatible issue between your module and HA.

Under RaspbianOS environment, the status icon of the sensor exactly can be updated in time on a Chromium page:
[https://drive.google.com/open?id=1FAyl8quM9l2Fd3i_902z6F5lkxH2WciW](https://drive.google.com/open?id=1FAyl8quM9l2Fd3i_902z6F5lkxH2WciW)

But after I added the HA home page into  MMM-SmartWebDisplay module, I found that the status icon of the sensor CANNOT be updated:
[https://drive.google.com/open?id=1XlfymFwzk-zms2tIF02yZx-KOg_x0EjM](https://drive.google.com/open?id=1XlfymFwzk-zms2tIF02yZx-KOg_x0EjM)

Maybe the MMM-SmartWebDisplay module blocks some messages, which are send by HA to "client" windows.

Can you help me to resolve this issue?  I'd be grateful if you would help me.
Thanks in advance.

**Comment by AgP42** [comment] 2019-04-09 19:35
Hello @xuepgao, 

thanks for those gif, that's very clear !

Infortunately I guess the issue is more coming from incompatibility between Home Assistant and iFrames and not directly on my module. Did you experiment the same behavior with other iFrame modules ?
As I don't have Home Assitant myself it will be hard to debug such case...

Good luck, 
AgP42

**Comment by xuepgao** [comment] 2019-04-10 13:32
Hi @AgP42 

Thanks for your reply.

According to your suggestion, I test other modules: your [MMM-iFrame-ping](https://github.com/AgP42/MMM-iFrame-Ping) and @alberttwong 's  [MMM-iFrame](https://github.com/alberttwong/MMM-iFrame).

in module [MMM-iFrame-ping](https://github.com/AgP42/MMM-iFrame-Ping), the issue is same.  The comforting thing is that its refresh function works fine. Although the status icon of the sensor CANNOT be updated, the status will be exact after the page refresh automatically.
 
in module [MMM-iFrame](https://github.com/alberttwong/MMM-iFrame), the screen is black. Nothing appears on my screen.

Could you tell me how to collect your two modules' logs? I'd like to check messages between HA and your modules.

-xuepgao

**Comment by AgP42** [comment] 2019-04-14 19:53
Hi @xuepgao , 

you can see the log of my module by activating it on the config (logDebug: false)(this will work on my 2 modules), then you can see them with ctrl + Maj +i. This will gives you all the MagicMirror log, but there is a field to filter it, please type in "SmartWebDisplay" or "iFrame-Ping" to view only those module infos. 
Then it is possible to export the logs. 
You can then send them to me here so I can also try to see if any solution can be apply. 

Bye, 
AgP42

**Comment by xuepgao** [comment] 2019-04-15 04:14
Hi @AgP42 

I configured logDebug:true and reloaded MagicMirror.

The following are log files:
[https://drive.google.com/open?id=1vFYd1vCsctXowGiWVSyBsKRm7jg9rGdf](https://drive.google.com/open?id=1vFYd1vCsctXowGiWVSyBsKRm7jg9rGdf)
[https://drive.google.com/open?id=1RLQgZbje5hHLbUvN_YpI162SbD6a8msr](https://drive.google.com/open?id=1RLQgZbje5hHLbUvN_YpI162SbD6a8msr)

There are 30 lines logs "Uncaught (in promise) TypeError: this.toggleAttribute is not a function". I don't understand what does it mean.

Please help me. Thanks again!

xuepgao

**Comment by AgP42** [comment] 2019-09-02 17:24
hi @xuepgao, 

sorry that I forget to answer your last email with the logs, I hope you were able to find a solution since then. 

Anyway the problem is for me on the original web page that you try to display. 

Here is the documentation about that error :
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function)

Maybe with some update of "Home assistant" or some update of magicmirror core it may work on the future, but on my module code I don't see what can I do...

Good luck !

**Comment by AgP42** [comment] 2019-10-07 18:32
Hi @xuepgao , 

sorry that I couldn't solve your problem, I hope you find another way !

As I don't see any solution for this issue, I close it. 

Bye, 
AgP

**Closed by AgP42** 2019-10-07 18:32 UTC
